pymisp/README.md
=> Change CIRCL to MISP repository

sharing/README.md
mention events, sharing groups and recommendations
=> first hackathon 2017

managing-feeds/README.md
````
it is totally described in the not yet written manual that is in my head and will one time surely make it into MISP-book
````
it is now also in MISP-book
=> mention manifest.json for local feeds

misp-zmq/README.md
I've added a couple tips for building subscribers and some explanations and examples of the different notification channels that MISP offers. Hopefully this helps build some more interesting apps that work with MISP in real time.
Please let me know if anything needs changing, thanks.
=> ZMQ Tips + Notification Examples

sightings/README.md
Open for suggestions, fixes #73
=> Clarify meaning of sighting as true positive

automation/README.md
I added some endpoints that have not been covered before, added example calls + output samples, re-ordered some endpoints 
to match the same topic (e.g. everything related to events) (that I believe have been historically grown) to make more sense
The work is not finished esp the error code handling is not complete. As well as all parameters to various endpoints.
Even if the PR looks weird, there is not a single point that has been removed, just re-ordered.
I also gave pymisp a little more love and moved it to the top.
=> Rewritten version

automation/README.md
https://github.com/MISP/MISP/issues/2861
=> lets document it then

GLOSSARY.md, README.md, SUMMARY.md, translation/README.md, translation/ja_JP.md
To the translation documents
Typos when obvious
Emphasize on MISP not it's full name
=> Various changes

GLOSSARY.md
Format:
Descriptive paragraph about Foo.
Src: https://toolchain.gitbook.com/lexicon.html
Also: Added by-line for Wikipedia happiness…
=> Fixed glossary. It needs h2 tags

shortcuts/README.md
See https://github.com/MISP/MISP/pull/2906
=> Add documentation for shortcuts in MISP.

automation/README.md
Documentation to use the new feature to can call misp-modules from API.
=> Use new Modules Controller

automation/README.md
=> add POST attributes/add

automation/README.md
to warn people not make a mistake
=> POST restfulSearch

automation/README.md
objects are exempt from the duplicate restrictions
=> file upload duplicates mention in the readme

GLOSSARY.md, administration/README.md, general-layout/README.md, misp-zmq/README.md
=> Use GnuPG consistently

sharing/README.md, sharing/figures/misp-sync-servers.svg
Some additional details on Sharing / Synchronisation mechanisms
=> Some additional details on Sharing / Synchronisation

quick-start/README.md
Modify Quick Start Page to add:
- Default Login into MISP
- Tasks to do after first Start
=> modify Quick Start Page

automation/README.md
I've added the 3 different sightings types to the automation page
=> Sightings types

taxonomy/README.md, warninglists/README.md
A section about warning list is the taxonomy page.
=> Moves Warning List information from taxonomy page.

USAGE.md, book.json, faq/README.md, galaxy/README.md, galaxy/gen-doc.sh, publish.sh
New: [plugin] added last modified
=> Chg: [doc] various sections updated in galaxy 

USAGE.md, book.json
Added more updates to plugin usage.
=> chg: [doc] Various updates to USAGE and documentation on plugins

USAGE.md, book.json
Added more updates to plugin usage.
=> chg: [fix] Fixed fontsettings plugin. It must be before CSS invocations.

faq/README.md
As per https://github.com/MISP/MISP/issues/3722
=> new: [doc] Added note on re-adding admin user

GLOSSARY.md, connectors/README.md
Added instructions on how to setup the connector and configure it to send events into Azure Sentinel
=> Microsoft Azure Sentinel MISP Connector

faq/README.md
Encountered this issue and received help on gitter. It was suggested to add my problem to the FAQ.
=> add column not found issue to FAQ

delegation/README.md
Following this issue MISP/MISP#4799, I add the prerequisite.
=> Add prerequisite for delegation

automation/README.md
Replace a real(?) API key with a dummy
=> Replace API key with dummy

book-convention/README.md
=> DOC: improve README.md (minor) spelling

general-concepts/README.md, using-the-system/README.md
Hello !
I fixed two typos that were making comprehension harder.
Regards
=> fixed two typos

delegation/README.md
Added agreed upon text mentioned in the issue.
=> chg: fix #202 - clarify delegation of event design

faq/README.md
I hadn't spotted that question before :/, updating with reference to how to set baseurl from cli.
=> chg: [FAQ] Improve redirected to localhost error question response

administration/README.md
Mainly fixing issue with heading levels
Also merged two redundant headings, changed blacklist to blocklist and updated the blocklist text a bit.
Blocklist section still needs to be expanded (for example with event block rules), might make an issue for that if it doesn't exist and will look into it later.
=> chg: Fix administration heading levels

automation/README.md
Add some extra description and examples.
close #233 as well.
=> chg: [API] update removeTagFromObject documentation.

managing-feeds/README.md
Replacing "bottom" with "button"
=> Fixing a typo

sharing/README.md
Saw https://github.com/MISP/MISP/commit/76a2727583abc9fd6405217c11ae6b0efa7046ee
Updating accordingly
There is a small bug that makes it so part of this is not entirely correct but I'll open something on MISP repo for that
=> chg: [sharing] update visibility of data to align with latest version

administration/README.md
To be merged together with https://github.com/MISP/MISP/pull/7242
=> chg: [Administration] add enableTaxonomyTags cli command

automation/README.md
See https://gitter.im/MISP/MISP?at=607fd4c5b6a4714a29d9d86a for reference
=> chg: [automation] add doc for /events/restSearch order parameter

warninglists/README.md
=> logical typo
